import "../styles/global.css"
import { Nav } from "../components/navigation"
import { StoreProvider } from "./StoreProvider"
import { TitlePanel } from "@/components/panel/title"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="bg-blue-gray-50">
          <Nav />
          <TitlePanel />

          <div className="pt-1">
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  )
}
